# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - myapp1229

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Build the app
        run: yarn build
      - name: Archive the app
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./tictactoe/dist/tictactoe  # Replace this with the actual path to your build output folder
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./tictactoe/dist/tictactoe

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: ${{ github.workspace }}/dist/tictactoe  # The path where you want to download the artifact

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myapp1229'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B8C8617CA1F64BEEB96C5B2BB9941B8A }}
          package: .
